### ISSUE TITLE
Properly implement AsgiRequest._stream

### ISSUE THREAD

**Issue by dav20011** [django/channels#1171] opened 2018-10-16 19:31 UTC
Django requests only contain a stream for the request body and lazy load the `request.body` property if needed. This is very intuitive because you can handle tasks like a file upload without loading the entire file into the memory while keeping the possibility of easily accessing the request body.

AsgiRequests on the other hand load the entire body before the execution of the view and only offer a fake stream. Looking at this code, it seems perfectly doable to handle this exactly like Django does by default. There actually is a TODO for this feature in the code, but I think it was forgotten. https://github.com/django/channels/blob/9c599380dde487912005133c01ca33a8b6e1d02a/channels/http.py#L119-L123

**Comment by andrewgodwin** [comment] 2018-10-17 08:11
It was not forgotten, just not implemented yet, since it's a bit trickier to stream this successfully. It should, however, be implemented as you suggest, so I'll leave this open as an enhancement (as it would improve memory efficiency).

**Comment by blueyed** [comment] 2019-05-06 04:33
Duplicate of https://github.com/django/channels/issues/1001 ?

**Comment by carltongibson** [comment] 2022-07-25 18:08
Closing as-per #1001: this'll be part of Django now.

**Closed by carltongibson** 2022-07-25 18:08 UTC
Labels: enhancement, exp/intermediate
