### ISSUE TITLE
Similar issue to #1369 - subprotocol response on Chrome

### ISSUE THREAD

**Issue by alex-yobota** [django/channels#1448] opened 2020-05-08 01:30 UTC
Hello. I'm having a similar issue to #1369 
Apparently, a common hack for authenticating websockets with token authentication is to put the token in the subprotocol argument of the websocket connection. I've done this, with the following AuthMiddleware:
```
@database_sync_to_async
def validate_token(token):
    auth = TokenAuthentication()
    return auth.authenticate_credentials(token.encode("utf-8"))


@database_sync_to_async
def close_connections():
    close_old_connections()


class WebsocketTokenAuthMiddleware:
    def __init__(self, inner):
        self.inner = inner

    def __call__(self, scope):
        close_connections()
        try:
            token = scope["subprotocols"][0]
            scope["user"] = validate_token(token)
            return self.inner(scope)
        except Exception:
            pass
```
This works fine on Firefox, but gives the same error as described in the linked issue on Chrome. This is running locally, via Daphne.

**Comment by nrehm** [comment] 2020-05-27 12:12
Having the same issue with the token based auth "hack" on chrome. 
Anyone found a solution?

**Comment by carltongibson** [comment] 2020-07-13 16:59
Duplicate of #1369. Let's keep the discussion there please.

**Closed by carltongibson** 2020-07-13 16:59 UTC
