### ISSUE TITLE
the service run for a while ，but don't push the message sudden,  you have to restart the service. Why is that?

### ISSUE THREAD

**Issue by xiaoqiao99** [django/channels#1271] opened 2019-03-28 11:24 UTC

**Comment by hishnash** [comment] 2019-03-30 05:12
@xiaoqiao99 could you provide some more details about your setup, 

what channel layer are you using, what version of channels, Django etc?

**Comment by xiaoqiao99** [comment] 2019-03-30 05:34
channels==2.1.7
channels-redis==2.3.3
beatserver==0.0.6

**Comment by hishnash** [comment] 2019-03-30 05:45
can you describe your issue a little more as well :)

as I understand you are running the server and after a while (how long?) it stops responding and you need to restart it?

can you still send messages to the server? 

what messages stop sending?

**Comment by xiaoqiao99** [comment] 2019-03-30 06:33
redis_version:4.0.10    
The service did not report an error . About six or ten hours later, 
the page will not receive messages  and server did not receive heartbeat.，the connecttion  is  good.
the page use https://github.com/zimv/websocket-heartbeat-js

**Comment by qeternity** [comment] 2019-03-30 15:47
@xiaoqiao99 are you running behind nginx?

**Comment by xiaoqiao99** [comment] 2019-03-31 01:21
yes. nginx  +  supervisor

**Comment by qeternity** [comment] 2019-03-31 14:45
Please see this comment https://github.com/django/channels/issues/1244#issuecomment-478258245

**Comment by carltongibson** [comment] 2019-04-05 16:36
Closing as a likely Duplicate of #1244.

**Closed by carltongibson** 2019-04-05 16:36 UTC
