### ISSUE TITLE
No option to send message immediately

### ISSUE THREAD

**Issue by CarneyC** [django/channels#2020] opened 2023-06-19 00:56 UTC
No option to send message immediately.
Immediately=True parameter was support in Channels 1.0 but no longer offers similar option for Channels 4.0 

e.g. When I receive a message, my backend sends back three different messages at different times. However, they all arrive at once.

**Comment by carltongibson** [comment] 2023-06-19 05:36
Channels was totally rearchitected for v2, and an immediate argument no
longer makes sense, as all messages have to go via the channel layer. Delivery should be quite prompt, and at most once, but if you need stricter ordering you'll need to build that yourself.

**Comment by carltongibson** [comment] 2023-06-19 05:37
Duplicate of #1284

**Closed** 2023-06-19 05:37 UTC
