### ISSUE TITLE
You cannot use AsyncToSync in the same thread as an async event loop - just await the async function directly.

### ISSUE THREAD

**Issue by ricleal** [django/channels#1020] opened 2018-04-16 18:19 UTC
Hello all,

Running the multichat example (andrewgodwin/channels-examples) I have the following issue:

```
[2018/04/16 18:11:18] WebSocket HANDSHAKING /chat/stream/ [127.0.0.1:56901]
2018-04-16 18:11:19,012 - ERROR - server - Exception inside application: You cannot use AsyncToSync in the same thread as an async event loop - just await the async function directly.
  File "/Users/rhf/.local/share/virtualenvs/multichat-fA-iSLTT/lib/python3.6/site-packages/channels/consumer.py", line 54, in __call__
    await await_many_dispatch([receive, self.channel_receive], self.dispatch)
  File "/Users/rhf/.local/share/virtualenvs/multichat-fA-iSLTT/lib/python3.6/site-packages/channels/utils.py", line 50, in await_many_dispatch
    await dispatch(result)
  File "/Users/rhf/.local/share/virtualenvs/multichat-fA-iSLTT/lib/python3.6/site-packages/channels/consumer.py", line 67, in dispatch
    await handler(message)
  File "/Users/rhf/.local/share/virtualenvs/multichat-fA-iSLTT/lib/python3.6/site-packages/channels/generic/websocket.py", line 173, in websocket_connect
    await self.connect()
  File "/Users/rhf/git/channels-examples/multichat/chat/consumers.py", line 26, in connect
    if self.scope["user"].is_anonymous:
  File "/Users/rhf/.local/share/virtualenvs/multichat-fA-iSLTT/lib/python3.6/site-packages/django/utils/functional.py", line 215, in inner
    self._setup()
  File "/Users/rhf/.local/share/virtualenvs/multichat-fA-iSLTT/lib/python3.6/site-packages/django/utils/functional.py", line 349, in _setup
    self._wrapped = self._setupfunc()
  File "/Users/rhf/.local/share/virtualenvs/multichat-fA-iSLTT/lib/python3.6/site-packages/channels/auth.py", line 142, in <lambda>
    scope["user"] = SimpleLazyObject(lambda: async_to_sync(get_user)(scope))
  File "/Users/rhf/.local/share/virtualenvs/multichat-fA-iSLTT/lib/python3.6/site-packages/asgiref/sync.py", line 34, in __call__
    "You cannot use AsyncToSync in the same thread as an async event loop - "
  You cannot use AsyncToSync in the same thread as an async event loop - just await the async function directly.
[2018/04/16 18:11:19] WebSocket DISCONNECT /chat/stream/ [127.0.0.1:56901
```

My versions are:

```
$ pip freeze
aioredis==1.0.0
asgiref==2.3.0
async-timeout==2.0.1
attrs==17.4.0
autobahn==18.4.1
Automat==0.6.0
channels==2.1.0
channels-redis==2.1.1
constantly==15.1.0
daphne==2.1.0
Django==2.0.4
hiredis==0.2.0
hyperlink==18.0.0
idna==2.6
incremental==17.5.0
msgpack==0.5.6
pytz==2018.4
six==1.11.0
Twisted==17.9.0
txaio==2.10.0
zope.interface==4.4.3

$ uname -a
Darwin mac95686 17.4.0 Darwin Kernel Version 17.4.0: Tue Dec 19 10:52:05 PST 2017; root:xnu-4570.47.16~1/RELEASE_X86_64 x86_64
```

Any help to solve this would be appreciated.
Thanks

**Comment by andrewgodwin** [comment] 2018-04-16 18:30
Hello - this is a duplicate of https://github.com/django/channels/issues/1017.

**Closed by andrewgodwin** 2018-04-16 18:30 UTC
