### ISSUE TITLE
Unexpected ASGI message 'http.response.start' sent, after response already completed.

### ISSUE THREAD

**Issue by alexanderhudym** [django/channels#1598] opened 2020-12-20 22:22 UTC
I have http and ws routings
when i try to make some rest request i receive 500 server error. In logs it look like
```
File "/app/.heroku/python/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
2020-12-20T22:18:17.155364+00:00 app[web.1]:     result = await app(self.scope, self.receive, self.send)
2020-12-20T22:18:17.155365+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
2020-12-20T22:18:17.155365+00:00 app[web.1]:     return await self.app(scope, receive, send)
2020-12-20T22:18:17.155365+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/channels/routing.py", line 71, in __call__
2020-12-20T22:18:17.155366+00:00 app[web.1]:     return await application(scope, receive, send)
2020-12-20T22:18:17.155366+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/channels/http.py", line 200, in __call__
2020-12-20T22:18:17.155367+00:00 app[web.1]:     await self.handle(body_stream)
2020-12-20T22:18:17.155367+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/asgiref/sync.py", line 304, in __call__
2020-12-20T22:18:17.155367+00:00 app[web.1]:     ret = await asyncio.wait_for(future, timeout=None)
2020-12-20T22:18:17.155368+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/asyncio/tasks.py", line 388, in wait_for
2020-12-20T22:18:17.155368+00:00 app[web.1]:     return await fut
2020-12-20T22:18:17.155376+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/concurrent/futures/thread.py", line 57, in run
2020-12-20T22:18:17.155377+00:00 app[web.1]:     result = self.fn(*self.args, **self.kwargs)
2020-12-20T22:18:17.155377+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/asgiref/sync.py", line 343, in thread_handler
2020-12-20T22:18:17.155378+00:00 app[web.1]:     return func(*args, **kwargs)
2020-12-20T22:18:17.155378+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/channels/http.py", line 258, in handle
2020-12-20T22:18:17.155378+00:00 app[web.1]:     self.send(response_message)
2020-12-20T22:18:17.155379+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/asgiref/sync.py", line 147, in __call__
2020-12-20T22:18:17.155379+00:00 app[web.1]:     return call_result.result()
2020-12-20T22:18:17.155379+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/concurrent/futures/_base.py", line 425, in result
2020-12-20T22:18:17.155380+00:00 app[web.1]:     return self.__get_result()
2020-12-20T22:18:17.155380+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
2020-12-20T22:18:17.155381+00:00 app[web.1]:     raise self._exception
2020-12-20T22:18:17.155381+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/asgiref/sync.py", line 212, in main_wrap
2020-12-20T22:18:17.155382+00:00 app[web.1]:     result = await self.awaitable(*args, **kwargs)
2020-12-20T22:18:17.155382+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 541, in send
2020-12-20T22:18:17.155382+00:00 app[web.1]:     raise RuntimeError(msg % message_type)
2020-12-20T22:18:17.155383+00:00 app[web.1]: RuntimeError: Unexpected ASGI message 'http.response.start' sent, after response already completed.
```
It occurs some times

I using channels 3.0.2, django 3.1.4, djangorestframework 3.12.2

my profile looks like web: bin/start-pgbouncer gunicorn --max-requests 200 --max-requests-jitter 15 app.asgi:application -b 0.0.0.0:$PORT -w 4 -k uvicorn.workers.UvicornWorker

**Comment by carltongibson** [comment] 2020-12-24 11:21
Duplicate of #1578

**Closed by carltongibson** 2020-12-24 11:21 UTC
