### ISSUE TITLE
Static file are not loading during generating pdf from html.

### ISSUE THREAD

**Issue by tanvir0ahmmed** [django/channels#1848] opened 2022-05-23 06:00 UTC
**When I add 'channels' to the installed app, then static files load failed in generating pdf from HTML; but if I remove 'channels' from the installed app, then static file loads correctly.**
I use Weasyprint to generate pdf from html

**Comment by carltongibson** [comment] 2022-05-23 06:09
Duplicate of #1847

**Closed by carltongibson** 2022-05-23 06:09 UTC
