### ISSUE TITLE
Windows Python 3.8 Selector issue: Adding app to INSTALLED_APPS won't allow RUNSERVER

### ISSUE THREAD

**Issue by jgreen44** [django/channels#1441] opened 2020-04-09 17:28 UTC
When I place 'channels', into the INSTALLED_APPS, I cannot run the server:

- Your OS and runtime environment, and browser if applicable

> Windows 10, IntelliJ IDEA, Brave Browser

- A `pip freeze` output showing your package versions

> asgiref==3.2.5
> attrs==19.3.0
> autobahn==20.4.1
> Automat==20.2.0
> certifi==2020.4.5.1
> cffi==1.14.0
> channels==2.4.0
> constantly==15.1.0
> cryptography==2.9
> daphne==2.4.1
> Django==3.0.3
> hyperlink==19.0.0
> idna==2.9
> incremental==17.5.0
> olefile==0.46
> Pillow==7.0.0
> psycopg2==2.8.4
> pyasn1==0.4.8
> pyasn1-modules==0.2.8
> pycparser==2.20
> PyHamcrest==2.0.2
> pyOpenSSL==19.1.0
> pytz==2019.3
> service-identity==18.1.0
> six==1.14.0
> sqlparse==0.3.0
> Twisted==20.3.0
> txaio==20.4.1
> wincertstore==0.2
> zope.interface==5.1.0

- Console logs and full tracebacks of any errors

> Watching for file changes with StatReloader
> Exception in thread django-main-thread:
> Traceback (most recent call last):
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
>     fn(*args, **kwargs)
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\django\core\management\commands\runserver.py", line 10
> 9, in inner_run
>     autoreload.raise_last_exception()
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\django\utils\autoreload.py", line 76, in raise_last_ex
> ception
>     raise _exception[1]
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\django\core\management\__init__.py", line 357, in exec
> ute
>     autoreload.check_errors(django.setup)()
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
>     fn(*args, **kwargs)
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\django\__init__.py", line 24, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\django\apps\registry.py", line 91, in populate
>     app_config = AppConfig.create(entry)
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\django\apps\config.py", line 116, in create
>     mod = import_module(mod_path)
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\importlib\__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\channels\apps.py", line 6, in <module>
>     import daphne.server
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\daphne\server.py", line 20, in <module>
>     asyncioreactor.install(twisted_loop)
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\twisted\internet\asyncioreactor.py", line 320, in inst
> all
>     reactor = AsyncioSelectorReactor(eventloop)
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\twisted\internet\asyncioreactor.py", line 69, in __ini
> t__
>     super().__init__()
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\twisted\internet\base.py", line 571, in __init__
>     self.installWaker()
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\twisted\internet\posixbase.py", line 286, in installWa
> ker
>     self.addReader(self.waker)
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\twisted\internet\asyncioreactor.py", line 151, in addR
> eader
>     self._asyncioEventloop.add_reader(fd, callWithLogger, reader,
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\asyncio\events.py", line 501, in add_reader
>     raise NotImplementedError
> NotImplementedError

**Comment by jgreen44** [comment] 2020-04-09 18:51
Hi @carltongibson : Thank you for responding. I will have to research how to install that branch and will get back to you when I find out how to do it.

**Comment by carltongibson** [comment] 2020-04-09 18:53
See the pip link. It gives you the incantations. (I’m away from the computer now so can’t put it together for you.)

Alternatively, you can use Python 3.7 for now.

**Comment by jgreen44** [comment] 2020-04-09 19:22
I downgraded Python 3.8 to 3.7:

> (DjangoProductHunt) C:\Users\Green\Google Drive\Development\Django Projects\chat - project\mysite>python
> Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)] :: Anaconda, Inc. on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>>

Unfortunately, when running server, I get:

> (DjangoProductHunt) C:\Users\Green\Google Drive\Development\Django Projects\chat - project\mysite>python manage.py ru
> nserver
> Watching for file changes with StatReloader
> Exception in thread django-main-thread:
> Traceback (most recent call last):
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\threading.py", line 917, in _bootstrap_inner
>     self.run()
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\threading.py", line 865, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\django\utils\autoreload.py", line 53, in wr
> apper
>     fn(*args, **kwargs)
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\django\core\management\commands\runserver.p
> y", line 109, in inner_run
>     autoreload.raise_last_exception()
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\django\utils\autoreload.py", line 76, in ra
> ise_last_exception
>     raise _exception[1]
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\django\core\management\__init__.py", line 3
> 57, in execute
>     autoreload.check_errors(django.setup)()
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\django\utils\autoreload.py", line 53, in wr
> apper
>     fn(*args, **kwargs)
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\django\__init__.py", line 24, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\django\apps\registry.py", line 91, in popul
> ate
>     app_config = AppConfig.create(entry)
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\django\apps\config.py", line 116, in create
> 
>     mod = import_module(mod_path)
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\importlib\__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\channels\apps.py", line 6, in <module>
>     import daphne.server
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\daphne\server.py", line 33, in <module>
>     from .ws_protocol import WebSocketFactory
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\daphne\ws_protocol.py", line 6, in <module>
> 
>     from autobahn.twisted.websocket import (
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\autobahn\twisted\__init__.py", line 54, in
> <module>
>     from autobahn.twisted.wamp import ApplicationSession
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\autobahn\twisted\wamp.py", line 48, in <mod
> ule>
>     from autobahn.wamp import protocol, auth
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\autobahn\wamp\auth.py", line 40, in <module
> >
>     from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\cryptography\hazmat\primitives\kdf\pbkdf2.p
> y", line 12, in <module>
>     from cryptography.hazmat.primitives import constant_time
>   File "C:\Users\Green\anaconda3\envs\DjangoProductHunt\lib\site-packages\cryptography\hazmat\primitives\constant_tim
> e.py", line 11, in <module>
>     from cryptography.hazmat.bindings._constant_time import lib
> ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._constant_time'
> 

I will research on how to install the branch you're referring to.

**Comment by carltongibson** [comment] 2020-04-09 19:34
```

ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._constant_time'

```

I’d try rebuilding you venv, and reinstalling requirements. 

Not something I can really help you to debug at this point.

**Comment by carltongibson** [comment] 2020-04-13 14:05
Here's the snippet to insert before importing daphne on Windows plus Python 3.8. 

```
import asyncio 
asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

Looking to a Daphne release doing this here https://github.com/django/daphne/pull/315

**Comment by carltongibson** [comment] 2020-04-13 14:12
I'm going to close this as it's a Duplicate of #1396

**Closed by carltongibson** 2020-04-13 14:12 UTC
