### ISSUE TITLE
group_send() not calling callback function

### ISSUE THREAD

**Issue by rgeller** [django/channels#1191] opened 2018-11-19 22:53 UTC
We are creating a chat application using React and Django with Channels. Intermittently, messages will suddenly stop showing up in the chat room for both sides (the sender and the recipient). However, when you refresh the chat, they will show up, meaning they're being added to our database, but not being received by our JS front-end/WebSocket client. 

Once it fails once, it never succeeds again until you refresh the page and, presumably, the websocket connection. Interestingly, when you restart the Django server, it starts working again, until it fails again.

I'm using Mac OS X 10.13.1, Django 2.1.3, Channels 2.1.5, Chrome 70, using the Django dev runserver, and redis on a remote server. (Redis is logging/receiving the data just fine, so I don't believe it's a network or redis issue.)

Here's the relevant code in our consumers.py:

```
### this is called by receive() depending on what the command is that's sent by our front-end
def new_message(self, data):
        author = data['from']
        text = data['text']
        author_user, created = User.objects.get_or_create(username=author)
        message = Message.objects.create(author=author_user, content=text,chat_room = self.chat)
        content = {
            'command': 'new_message',
            'message': self.message_to_json(message)
        }
        self.send_chat_message(content)
```

```
### this is called by new_message()
    def send_chat_message(self, message):
        # Send message to room group
        async_to_sync(self.channel_layer.group_send)(
            self.room_name,
            {
                'type': 'chat_message',
                'message': message
            }
        )
```

```
### this is called per the "type" parameter in the group_send() function call above
    def chat_message(self, event):
        message = event['message']
        # Send message to WebSocket
        self.send(text_data=json.dumps(message))
```

It appears that when this problem starts happening, the callback function "chat_message()" from (async_to_sync)(group_send) stops being called.

I tried rewriting the entire consumers.py module using JsonWebsocketConsumer and spent hours trying to modify the front-end to accommodate that, but the problem persisted, albeit perhaps not as badly.

I appreciate your help in advance.

**Comment by andrewgodwin** [comment] 2018-11-19 23:01
So the Javascript code is not something we support any more, so what we'd need you to do here is narrow it down to something reproduceable on the network level - seeing that there are no more incoming WebSocket frames - and that you can make this happen on any host in an example project. Once we get that, we can reproduce this and help solve it if it's a channels issue.

I'll leave this open for a bit to see if we can get that far, otherwise I'll have to close it as nonreproduceable!

**Comment by rgeller** [comment] 2018-11-19 23:08
Thank you, Andrew. We are able to make this work on three hosts. Moving it
to a different project just to troubleshoot is not really a practical
option until we're able to eliminate any other possible causes.

However, I can tell you that it's clear that the callback function,
chat_message(), is *not* being called on the server side, because we put a
print() statement in the first line of that function and it's not being
printed.

*Robert Geller*
rgeller@instantek.com
IT Support: support@instantek.com
Phone: 646.854.8488
www.instantek.com

**Comment by andrewgodwin** [comment] 2018-11-19 23:21
Ah, I see. Still, without the ability to reproduce this there's not really much we can do to help - this could be any number of issues from the Redis layer through to mismatched libraries on your end. If we can't get steps to reproduce I'm going to have to close this as a GitHub issue and ask you to go use django-users or stackoverflow instead and see if anyone else can help (see https://channels.readthedocs.io/en/latest/support.html) - unfortunately I only have time here to work on replicatable, confirmed issues.

**Comment by rgeller** [comment] 2018-11-20 00:19
Hi Andrew,

I understand this, but we have been beating our heads (3 of them!) against
a wall troubleshooting this for 20+ hours. From what I've found, the
group_send and other functions are sparsely documented, which makes it
difficult to implement them. We're just stabbing in the dark and emulating
examples without a real understanding of how things work.

Can you please tell me if our code is correct? I think others in the future
will find this helpful, as well. I have worked from your multichat example
on github but that uses an async consumer and we're not using async.
(Should we be?)

Thank you,

Robert

*Robert Geller*
rgeller@instantek.com
IT Support: support@instantek.com
Phone: 646.854.8488
www.instantek.com

**Comment by rgeller** [comment] 2018-11-20 01:06
We found other folks on Stackoverflow having the same exact or very similar issues:

- https://stackoverflow.com/questions/52224019/django-channels-2-stops-sending-message-after-a-while-but-keeps-receiving-from-c
- https://stackoverflow.com/questions/45190185/django-channels-group-send-stop-working?s=1|109.6777
- https://stackoverflow.com/questions/51024893/how-do-i-send-channels-2-x-group-message-from-django-celery-3-task

There are very few authoritative answers (or answers at all in some cases).

It would be great if you could clear up how to use group_send properly or if there are any issues in our code, which as I mentioned would likely help a lot of people.

**Comment by andrewgodwin** [comment] 2018-11-20 18:37
You appear to be using group_send properly in the examples you've given - the thing I would look for is not on the sending end, but on the receiving end. Because the receiver runs in a single async loop, if you blocked in a receiver and took too long you might miss the next message (because the handler has to finish before the next message is received).

Best thing to do for further debugging is to directly MONITOR Redis and see if your sends are going through (they should be an `LPUSH`) and then you can work out what end the problem is.

Going to close this ticket for now as it does not appear to be an issue in Channels directly, but we can keep chatting.

**Closed by andrewgodwin** 2018-11-20 18:37 UTC
Labels: blocked/user-response

**Comment by whitexozu** [comment] 2018-12-18 18:30
Change the channels-redis version
It is expected with the channels-redis == 2.3.2 bug.
