### ISSUE TITLE
ERR_CONNECTION_RESET after upgrade to 1.0.2 from 0.17.3

### ISSUE THREAD

**Issue by codyparker** [django/channels#488] opened 2017-01-17 21:03 UTC
Hello, first of all - thanks for this awesome addition to Django!

I had a fully working app with 0.17.3 and an upgrade to the latest version caused a bit of an issue that I can't track down. 

**Issue:** When I create a websocket connection, it appears to reach the consumers.py and connect without a problem initially. After a few seconds I receive an error in browser console of:
_WebSocket connection to 'ws://127.0.0.1:8080/lobby/' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET_ 

If I don't wait for the error and click on a button that sends a request to the channels backend, I get: _DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING stat_ , and that is followed by the previous error I mentioned.

Those are the only two errors I see, and there are no errors in my runserver output. I just get a 

**Working Versions:**
channels - 0.17.3
daphne - 0.15.3
Django - 1.9
Twisted - 16.6.0

**Non Working Versions:**
channels - 1.0.2
daphne - 1.0.1
Django - 1.9
Twisted - 16.6.0

**More info:** 

- I'm using route_class in my **router.py**:
`channel_routing = [
    route_class(consumers.LobbyConsumer,  path=r"^/lobby/"),
    route_class(consumers.GameConsumer,  path=r"^/game/(?P<game_id>\d+)/$")
]`

- I've tried Firefox and Chrome, as well as using http://127.0.0.1 and http://localhost as well as different ports (before http://localhost:8080 worked fine). I'm also just running this in _runserver_.
- This also happens in both Linux and OSX.
- I'm using React working as a front-end, connecting with [react-websocket](https://github.com/mehmetkose/react-websocket)
- The only change I've made was to remove and reinstall channels (and dependencies) with the latest version. I have two virtualenvs that I can switch between and see it work, and then not work with the newer versions.

I thought I was on the right track by looking at Daphne's server module (server.py), but I never could track it down. 

Hopefully you can help guide me in the right direction if this isn't a channels issue. Thank you for your time!

**Comment by LeonKoole** [comment] 2017-01-17 21:38
Since you say the only change you've made is reinstalling channels to the latest version, I'm assuming the issue is that you are not accepting the WebSocket connection in your consumer. Since 1.0.0 WebSockets must now be explicitly accepted or denied [(see the 1.0.0 release notes)](https://channels.readthedocs.io/en/latest/releases/1.0.0.html). Hopefully this fixes the issue.

**Comment by andrewgodwin** [comment] 2017-01-17 21:40
Yes, this seems very much like not accepting the requests in the connect handler to me, as the linked release notes suggest. I'm close to preliminarily close this ticket for that reason - feel free to reopen if it's not that.

**Closed by andrewgodwin** 2017-01-17 21:40 UTC

**Comment by codyparker** [comment] 2017-01-17 22:09
Welp...I read that earlier in the latest docs, but then lost my reading skills when it came to the comment in the example:  `#Accept the connection; this is done by default if you don't override the connect function.`

I thought this would happen automatically after reading "this is done by default"...the rest of the sentence is important as well. 

That fixed it, of course! Thanks to you both for your help.
