### ISSUE TITLE
Channels 2 appears 10-20 times slower than channels 1 

### ISSUE THREAD

**Issue by sebhaase** [django/channels#1011] opened 2018-04-10 09:49 UTC
One point in the docs I noticed was regarding the `enforce_ordering` in channels 1:
https://channels.readthedocs.io/en/1.x/getting-started.html#enforcing-ordering

For channels 2, it says that ordering is always enforced.  Is it possible that channels2 is "slower by design" ;-) ?

ref.: 
http://channels.readthedocs.io/en/latest/one-to-two.html?highlight=ordering#channel-session-and-enforce-ordering :
> ...enforce_ordering decorators can be removed; ordering is now always followed as protocols are handled in the same process

Thanks.

**Comment by andrewgodwin** [comment] 2018-04-10 17:00
No, Channels 2 is significantly faster by design as all events are handled in the same process rather than across a network. Unless there's a further question to this issue, I will have to close it...?

**Closed by andrewgodwin** 2018-04-10 17:00 UTC

**Comment by sebhaase** [comment] 2018-04-10 20:02
Thanks for the answer. So you are saying that Channels 2 should be fast even though it always enforces ordering (which did slow down Channels 1!) ?   
Our issue is that we see this gigantic slowdown after migrating to channels 2 (so far using synchronous classes).   I think I saw somewhere another issue where group-send was reported to be slow after migration... !?

**Comment by hishnash** [comment] 2018-04-10 20:14
@sebhaase what i have notices that if you have multiple concurrent messages (WebSocket frames) from the same connection being prosses in channels 2 these are much slower since at least as I understand it there is one instance (per WebSocket connection) and one run loop working on these. So in my case when the app sends 5 messages to subscribe those, in the end, are proses sequentially but on the same worker rather than in channels 1 was they were processed at the same time but on different workers.

**Comment by andrewgodwin** [comment] 2018-04-10 23:25
Unfortunately I have not had the time or the resources to sit down and do performance testing, so I don't know the difference, but it would be worth if you are talking about processing frames from the same client versus different clients, as Channels 2 will always handle a single client synchronously (the async is just handoffs between multiple client consumers)

**Comment by sebhaase** [comment] 2018-04-11 12:41
We took out the group-send as reply to incoming messages and it got fast again ...
That lets us think that it might be the exact same problem as in the other issue I already cited.

So we hope you have time to look into the redis problem , b/c right now channels 2 appears to be unusable without group-send ... 
Andrew, Thanks for all you work you are putting into this !

**Comment by andrewgodwin** [comment] 2018-04-11 17:17
Ah yes, that would explain it. Have you tried the master branch of `channels-redis` and the new lua-based group send? It's still buggy but should be a lot faster.
