### ISSUE TITLE
Testing with multiple asyncio loops and RedisChannelLayer

### ISSUE THREAD

**Issue by laevilgenius** [django/channels#876] opened 2018-02-06 21:40 UTC
Say, I have two unit tests and each has its own asyncio loop. In that case the first one will run successfully and the second one will fail with `Event loop is closed`. This happens because `ChannelLayerManager` caches `RedisChannelLayer` instance, which in turn caches `loop` instance. Running `channel_layers.backends.clear()` at the beginning of each test helps. I think, it should be mentioned in the docs.

**Comment by andrewgodwin** [comment] 2018-02-06 21:44
This is likely also related to https://github.com/django/channels/issues/859 - the `channels_redis` backend does a bit too much presumption about being run in a single loop right now. I intend to investigate tomorrow/this week.

**Comment by andrewgodwin** [comment] 2018-02-08 01:30
Closing as dupe of #859.

**Closed by andrewgodwin** 2018-02-08 01:30 UTC
Labels: bug, exp/advanced

**Comment by laevilgenius** [comment] 2018-02-21 15:12
I have this (or similar) problem again, channels stack is on `master`. Now it is related to using multiple communicators in a single test case:
```
class TestConsumer(WebsocketConsumer):
    def connect(self):
        self.accept()

    def receive(self, text_data=None, bytes_data=None):
        self.send(text_data=text_data, bytes_data=bytes_data)

    def disconnect(self, code):
        pass

class CommunicatorTestCase(TestCase):
    @async_test
    async def test_1(self):
        communicator1 = WebsocketCommunicator(TestConsumer, "/testws/")
        communicator2 = WebsocketCommunicator(TestConsumer, "/testws/")
        await communicator1.connect()
        await communicator2.connect()

        await communicator1.send_to(text_data="hello")
        await communicator1.receive_from()
        await communicator2.send_to(text_data="hello")
        await communicator2.receive_from()

        await communicator1.disconnect()
        await communicator2.disconnect()

    @async_test
    async def test_2(self):
        # channel_layers.backends.clear()

        communicator1 = WebsocketCommunicator(TestConsumer, "/testws/")
        communicator2 = WebsocketCommunicator(TestConsumer, "/testws/")
        await communicator1.connect()
        await communicator2.connect()  # fails here

        await communicator1.send_to(text_data="hello")
        await communicator1.receive_from()
        await communicator2.send_to(text_data="hello")
        await communicator2.receive_from()

        await communicator1.disconnect()
        await communicator2.disconnect()
```
It throws `Task <Task pending coro=<RedisChannelLayer.receive_loop() got Future attached to a different loop`.
`channel_layers.backends.clear()` still helps.

**Comment by dgilge** [comment] 2018-02-21 17:49
I just tried two communicators in one test and it worked in my case. I'm using `py.test` top-level test functions (as recommended in the [docs](http://channels.readthedocs.io/en/latest/topics/testing.html)). Maybe it's an option for you to avoid `TestCase` in your tests.

You might have to override the `event_loop` (in your conftest.py), though:

```python
@pytest.yield_fixture(scope='module')
def event_loop(request):
    try:
        loop = asyncio.get_event_loop()
    except RuntimeError:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
    yield loop
```

**Comment by andrewgodwin** [comment] 2018-02-21 18:07
Ah yes, I can't support anything other than the `pytest-asyncio` style tests, as other async test wrappers may not be managing event loops properly.

**Comment by laevilgenius** [comment] 2018-02-21 18:57
Doesn't work with `py.test` either:
```
@pytest.mark.asyncio
async def test_1():
    communicator1 = WebsocketCommunicator(TestConsumer, "/testws/")
    communicator2 = WebsocketCommunicator(TestConsumer, "/testws/")
    await communicator1.connect()
    await communicator2.connect()

    await communicator1.send_to(text_data="hello")
    await communicator1.receive_from()
    await communicator2.send_to(text_data="hello")
    await communicator2.receive_from()

    await communicator1.disconnect()
    await communicator2.disconnect()


@pytest.mark.asyncio
async def test_2():
    # channel_layers.backends.clear()

    communicator1 = WebsocketCommunicator(TestConsumer, "/testws/")
    communicator2 = WebsocketCommunicator(TestConsumer, "/testws/")
    await communicator1.connect()
    await communicator2.connect()  # fails here

    await communicator1.send_to(text_data="hello")
    await communicator1.receive_from()
    await communicator2.send_to(text_data="hello")
    await communicator2.receive_from()

    await communicator1.disconnect()
    await communicator2.disconnect()
```
Second test throws the same `Task <Task pending coro=<RedisChannelLayer.receive_loop() got Future attached to a different loop`. Note that this happens only for second test in both `py.test` and `unittest`.
`channel_layers.backends.clear()` works here as well.

**Comment by laevilgenius** [comment] 2018-02-21 19:32
Yes, everything works with today's update, thanks.
