### ISSUE TITLE
Setting SSLContext for wss (websocket secure) Channels consumer

### ISSUE THREAD

**Issue by MarcMueltin** [django/channels#1404] opened 2020-01-20 09:23 UTC
I am trying to figure out how to set an SSLContext (https://docs.python.org/3.8/library/ssl.html#ssl.SSLContext) for the TLS server I'm trying to set up using Django Channels so that it accepts my websocket connections via the wss:// scheme.

For ws:// without TLS everything works perfectly. I use the websockets package on my client side to set up a connection to the server (which runs Channels as an ASGI server). But when I shift to wss:// and start running the client, then ... nothing happens for 60s, after which I get an error message stating: "SSL handshake is taking longer than 60.0 seconds: aborting the connection"

My Daphne server is running on localhost with standard port 8000.

```
Starting ASGI/Channels version 2.2.0 development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
INFO - 2019-11-15 14:12:14,094 - django-main-thread - daphne.server[110] - HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO - 2019-11-15 14:12:14,094 - django-main-thread - daphne.server[119] - Configuring endpoint tcp:port=8000:interface=127.0.0.1
INFO - 2019-11-15 14:12:14,095 - django-main-thread - daphne.server[150] - Listening on TCP address 127.0.0.1:8000
```

The client-side connection is established like this (the ssl_context variable was set properly before):

```
async with websockets.client.connect(
                uri=url,
                extra_headers=header,
                subprotocols=['ocpp2.0'],
                ssl=ssl_context) as websocket:
            global ws
            ws = websocket
            await asyncio.gather(on_open(websocket), on_message(websocket))
```

The on_open() and on_message() methods handle the opening of the socket and parsing incoming messages, respectively.

Now, I was actually expecting to be able to set an SSL context on the server side (using Channels) as well, but I haven't found one single example after many hours of research online. I need to set the SSL context to define which cipher suite and which elliptic curve to use, etc.

Is there something fundamentally wrong in my approach that I haven't grasped yet?

**Comment by carltongibson** [comment] 2020-01-22 13:37
Duplicate of https://github.com/django/daphne/issues/306. TLS handshake with be Twisted/Daphne's responsibility (although probably better to use a reverse proxy, such as nginx).

**Closed by carltongibson** 2020-01-22 13:37 UTC
