### ISSUE TITLE
'module' object has no attribute 'FunctionType'

### ISSUE THREAD

**Issue by sento93** [django/channels#432] opened 2016-11-08 20:49 UTC
Channels connect but doesn't send.

In the worker console the following error is raised:

```
2016-11-08 21:38:26,407 - INFO - runworker - Using single-threaded worker.
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
  File "/Library/Python/2.7/site-packages/channels/asgi.py", line 86, in __str__
    return "%s (%s)" % (self.alias, name_that_thing(self.channel_layer))
  File "/Library/Python/2.7/site-packages/channels/utils.py", line 25, in name_that_thing
    return name_that_thing(thing.__class__)
  File "/Library/Python/2.7/site-packages/channels/utils.py", line 16, in name_that_thing
    if hasattr(thing, "__class__") and not isinstance(thing, (types.FunctionType, types.MethodType)):
AttributeError: 'module' object has no attribute 'FunctionType'
Logged from file runworker.py, line 71
```

Installed versions:
asgi-redis==1.0.0
asgiref==1.0.0
channels==0.17.3
daphne==0.15.0
Django==1.10.3
redis==2.10.5
txredisapi==1.4.3

**Comment by andrewgodwin** [comment] 2016-11-09 03:23
What version of Python are you using?

**Comment by KhasanovBI** [comment] 2016-11-09 05:26
May be there is a python file in your project with name `types.py`?

**Comment by sento93** [comment] 2016-11-09 09:01
@andrewgodwin Is in python 2.7.10 and OS X 10.11.6

**Comment by andrewgodwin** [comment] 2016-11-09 17:17
Do you have a module called `types.py` as suggested above? This looks like an import path issue, not a Channels issue.

**Comment by sento93** [comment] 2016-11-10 09:05
No, only the common files of Django and channels (apps, models, views, consumers...)

**Comment by KhasanovBI** [comment] 2016-11-10 09:15
@sento93 Try enter to ./manage.py shell
And pls send output of
```
>>> import types
>>> types
```

**Comment by sento93** [comment] 2016-11-14 09:31
<module 'types' from '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/types.pyc'>

**Comment by andrewgodwin** [comment] 2016-11-14 17:28
Are you sure this is in the same context/virtualenv you were running channels in? You should be able to do the following:

```import types
types.FunctionType```

and have it not error.

I'm pretty sure this is not a Channels bug as I can't reproduce it locally and it looks like a classic path mismatch, so closing it for now.

**Closed by andrewgodwin** 2016-11-14 17:28 UTC
Labels: blocked/user-response, bug

**Comment by jupiterkenji** [comment] 2016-12-09 17:05
I have the same issue. Inspecting the channels folder, I found types.py file
`# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from typing import Any, Dict


SendOptions = Dict[Any, Any]`

I renamed it and it works. I couldn't find that file in the github source though.
May be old file wrongly named types.py and conflicting with types module?

**Comment by andrewgodwin** [comment] 2016-12-10 01:24
You have installed the `django-channels` package (not this project) rather than the `channels` package.

**Comment by jupiterkenji** [comment] 2016-12-10 02:43
@andrewgodwin you are correct. First I installed django-channels and realized it was wrong and installed channels on top. Thank you for clearing this up =)

**Comment by svays** [comment] 2017-09-18 11:10
I also encounter with same issue and I did't install django-channels I have installed channel but again I saw that error.

`D:\schoolvirtualev\virtualenv\Scripts\python.exe "D:/School Project v2/ws-py-svyas/testing-app/multichat/manage.py" runserver localhost:8200
Performing system checks...

System check identified no issues (0 silenced).
September 18, 2017 - 16:36:21
Unhandled exception in thread started by <function wrapper at 0x03CD89B0>
Traceback (most recent call last):
  File "D:\schoolvirtualev\virtualenv\lib\site-packages\django\utils\autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "C:\Python27-13\lib\site-packages\channels\management\commands\runserver.py", line 73, in inner_run
    "layer": self.channel_layer,
  File "C:\Python27-13\lib\site-packages\channels\asgi.py", line 103, in __str__
    return "%s (%s)" % (self.alias, name_that_thing(self.channel_layer))
  File "C:\Python27-13\lib\site-packages\channels\utils.py", line 25, in name_that_thing
    return name_that_thing(thing.__class__)
  File "C:\Python27-13\lib\site-packages\channels\utils.py", line 16, in name_that_thing
    if hasattr(thing, "__class__") and not isinstance(thing, (types.FunctionType, types.MethodType)):
AttributeError: 'module' object has no attribute 'FunctionType'`

Can you please give solution of this..??

**Comment by proofit404** [comment] 2017-09-18 11:19
Please, read comments above. You can check if this is a `sys.path` issue in the interactive console.

```python
>>> import types
>>> types.__file__
'/home/proofit404/.pyenv/versions/3.6.1/lib/python3.6/types.py'
```

If the last expression doesn't give you system library, you should rename your module.

**Comment by svays** [comment] 2017-09-19 05:24
I get below result after running that commands..

`'C:\\Python27-13\\lib\\types.pyc'`

**Comment by proofit404** [comment] 2017-09-19 10:20
Does corresponding python source file contains `FunctionType` definition?

**Comment by proofit404** [comment] 2017-09-19 10:22
Does corresponding source file contains FunctionType definition?

**Comment by svays** [comment] 2017-09-20 03:38
Do I have to check on that file for  `FunctionType` or any other ...???

C:\Python27-13\Lib\py_compile.py

**Comment by proofit404** [comment] 2017-09-20 05:15
Check `C:\\Python27-13\\lib\\types.py`

**Comment by svays** [comment] 2017-09-20 06:57
Here is Types.py file 


`"""Define names for all type symbols known in the standard interpreter.

Types that are part of optional modules (e.g. array) are not listed.
"""
import sys

# Iterators in Python aren't a matter of type but of protocol.  A large
# and changing number of builtin types implement *some* flavor of
# iterator.  Don't check the type!  Use hasattr to check for both
# "__iter__" and "next" attributes instead.

NoneType = type(None)
TypeType = type
ObjectType = object

IntType = int
LongType = long
FloatType = float
BooleanType = bool
try:
    ComplexType = complex
except NameError:
    pass

StringType = str

# StringTypes is already outdated.  Instead of writing "type(x) in
# types.StringTypes", you should use "isinstance(x, basestring)".  But
# we keep around for compatibility with Python 2.2.
try:
    UnicodeType = unicode
    StringTypes = (StringType, UnicodeType)
except NameError:
    StringTypes = (StringType,)

BufferType = buffer

TupleType = tuple
ListType = list
DictType = DictionaryType = dict

def _f(): pass
FunctionType = type(_f)
LambdaType = type(lambda: None)         # Same as FunctionType
CodeType = type(_f.func_code)

def _g():
    yield 1
GeneratorType = type(_g())

class _C:
    def _m(self): pass
ClassType = type(_C)
UnboundMethodType = type(_C._m)         # Same as MethodType
_x = _C()
InstanceType = type(_x)
MethodType = type(_x._m)

BuiltinFunctionType = type(len)
BuiltinMethodType = type([].append)     # Same as BuiltinFunctionType

ModuleType = type(sys)
FileType = file
XRangeType = xrange

try:
    raise TypeError
except TypeError:
    tb = sys.exc_info()[2]
    TracebackType = type(tb)
    FrameType = type(tb.tb_frame)
    del tb

SliceType = slice
EllipsisType = type(Ellipsis)

DictProxyType = type(TypeType.__dict__)
NotImplementedType = type(NotImplemented)

# For Jython, the following two types are identical
GetSetDescriptorType = type(FunctionType.func_code)
MemberDescriptorType = type(FunctionType.func_globals)

del sys, _f, _g, _C, _x                           # Not for export

__all__ = list(n for n in globals() if n[:1] != '_')
`

**Comment by proofit404** [comment] 2017-09-20 07:39
Did you activate virtualenv before following instructions in this [comment](https://github.com/django/channels/issues/432#issuecomment-330191105)
