### ISSUE TITLE
IPCChannelLayer is unstable

### ISSUE THREAD

**Issue by bakatrouble** [django/channels#398] opened 2016-10-14 19:45 UTC
Title. In websocket consumer, receive method is often called twice or even three times (didn't happen more, yet), sometimes it loses messages. inmemory and redis channels are a lot more stable (switching to redis resolved the problem, as I could see).

I'm running my code on Digitalocean Debian 8.6 jessie box, two workers (runworker) and daphne runned using supervisord, web server is nginx simply redirecting everything to Daphne unix socket.

Python (3.4.2) package versions:

```
asgi-ipc==1.1.0
asgi-redis==0.14.1
asgiref==0.14.0
autobahn==0.16.0
channels==0.17.2
daphne==0.15.0
defusedxml==0.4.1
Django==1.10.1
django-allauth==0.27.0
jsonschema==2.5.1
msgpack-python==0.4.8
oauthlib==2.0.0
Pillow==3.3.1
posix-ipc==1.0.0
psycopg2==2.6.2
python3-openid==3.0.10
redis==2.10.5
requests==2.11.1
requests-oauthlib==0.7.0
six==1.10.0
Twisted==16.4.1
txaio==2.5.1
zope.interface==4.3.2
```

**Comment by andrewgodwin** [comment] 2016-10-16 01:51
Could you post the configuration you had in Django for the layer? How many daphne processes and runworkers did you have? And were there any console output messages?

The IPC layer is not recommended for production use really, but it would be nice if it didn't multi-deliver.

**Comment by bakatrouble** [comment] 2016-10-16 07:01
Single Daphne process on unix socket, two workers. There was no console
output. Configuration is the same as in docs: default ipc layer w/prefix.
Documentation mentions nothing about it's not recommended on "Deploying"
page though.

On Oct 16, 2016 4:51 AM, "Andrew Godwin" <notifications@github.com> wrote:

Could you post the configuration you had in Django for the layer? How many
daphne processes and runworkers did you have? And were there any console
output messages?

The IPC layer is not recommended for production use really, but it would be
nice if it didn't multi-deliver.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/django/channels/issues/398#issuecomment-254022167>, or mute
the thread

**Comment by andrewgodwin** [comment] 2016-10-16 17:48
How do you know you were getting duplication, then? Daphne logs that to the console output if it happens as an error, and you've have to run in verbose mode to see it on the worker, which would mean reams of console output.

I've just tried the same setup locally as well (ubuntu 16.04, so not worlds away from your OS) and see perfect delivery of messages. Some sort of steps to replicate would be great.

**Comment by jorrete** [comment] 2016-10-19 10:53
I think I can reproduce the same issue. Not able to reproduce it in local but happening on my server (Webfaction), also with ipc layer.

Same behavior, loosing some messages and answering duplicated or triplicated. Because in local can't reproduce it I am not able to set an example.
Also noted in my tests that happens when  I am sending two messages  in row, not happening if only send a message.

```
socket.send('foo')
socket.send('foo1')
```

**Comment by jorrete** [comment] 2016-10-19 11:15
[off-topic]
When you say:

> The IPC layer is not recommended for production use really

Do you mean never like memory layer or not ready yet?

I like the idea of deploy small sites without redis dependency.

**Comment by andrewgodwin** [comment] 2016-10-19 16:27
The Redis layer I know to be run on production sites with no issues and capable of handling a decent amount of load; in the Channels load tests, however, IPC performed relatively poorly, and I've not heard of it being used in proper production yet, so I would be cautious.

@jorrete what is the symptom that lets you know you have multiple message sends? Getting copies of the message you sent delivered to the websocket client?

**Comment by jorrete** [comment] 2016-10-19 16:34
Yes.
It happens if Firefox and Chrome. With "WS Extension" for Firefox DevTools I can see the same messages received several times, so that tells me that the problem is not a message event fired several times on client.

**Comment by bakatrouble** [comment] 2016-10-19 16:44
I put logging code in the receive function, and get duplicating log
entries, so I am sure I have this problem. Getting multiple echo messages
on websocket too. Didn't try IPC layer locally though.

**Comment by asmyshlyaev177** [comment] 2016-12-25 16:31
On centos 6.8 with django 1.10 same issue.

**Comment by andrewgodwin** [comment] 2017-04-06 07:15
Moving to https://github.com/django/asgi_ipc/issues/20

**Closed by andrewgodwin** 2017-04-06 07:15 UTC
Labels: blocked/user-response, bug
