### ISSUE TITLE
Error when trying to create or edit any model in django admin 

### ISSUE THREAD

**Issue by phrolov** [django/channels#1100] opened 2018-07-10 03:52 UTC
When trying to create or edit any model in Django admin the error occurs (browser shows it as "page not available"). It doesn't appear in Django log - it's like connection drop or something. The login procedure and deleting model item completes successfully. I notice the difference between these POST requests - login method content type is `application/x-www-form-urlencoded`, while add model item method is `multipart/form-data`. The problem disappears when channels app is not present in installed apps in `settings.py`.

The app is running from command line `manage.py runserver` with debug option on.
Python 3.7.0, django-2.0.7, channels-2.1.2, daphne-2.2.0, asgiref-2.3.2, twisted-18.4.0

**Comment by andrewgodwin** [comment] 2018-07-10 16:15
I'm going to need a lot more information than this to work out what's wrong, I'm afraid. Including:

* Is there any console output when this happens?
* Do you have any unusual settings?
* What OS are you running on?
* Does this still happen on a fresh project (or the multichat example in my channels-examples repo)?

I just checked on my local machine and the Django admin still works fine, so something about your installation is a bit off and to solve this, we need to work out what (and if it's a bug or just a misconfiguration)

**Comment by GDay** [comment] 2018-07-11 00:49
Can actually confirm this issue. In Chrome, I get a `HTTP ERROR 400`. There is no error message sent with it. This is only there for POST and PATCH requests. 

> Is there any console output when this happens?

Nope, both console and the network tab are completely empty in my browser. When I look at the server logs in terminal, it doesn't show the POST requests and PATCH requests. Somehow it looks like it blocks those before actually hitting the server. 

> Do you have any unusual settings?

Nope, I just installed Django Channels as per the documentation. I also installed DRF and a few other things, but I don't think it has to do with this issue.

> What OS are you running on?

I am running on OSX version 10.13.4 and have tried this with multiple browsers.

> Does this still happen on a fresh project (or the multichat example in my channels-examples repo)?

This is currently on a fresh project. 

FWIW: I just tried the multichat example in your channels-examples repo. I installed it with Python 3.7 and I got the same issue. Then I tried to installed it with python 3.6 and that worked fine. So I am pretty sure it's python 3.7 that is causing this somehow. 
Hopefully, you can reproduce it now.
Thanks!

**Comment by phrolov** [comment] 2018-07-11 03:35
I got the same results as @GDay and, yes, on Python 3.6 my application works fine. I'm using docker python:3 image which is Debian 9.4 (stretch) based.

**Comment by andrewgodwin** [comment] 2018-07-12 00:09
Ooh, Python 3.7, right. That I can probably try to get a reproduction.

**Comment by andrewgodwin** [comment] 2018-07-12 00:29
As far as I can tell this happens in Twisted, before it even gets to any of my code. I suspect it's https://twistedmatrix.com/trac/ticket/9448

**Comment by noufalvlpr** [comment] 2018-07-17 16:04
had the same issue with Django rest multi part file upload

**Comment by andrewgodwin** [comment] 2018-07-18 23:14
Have you tried using the latest Twisted release?

**Comment by noufalvlpr** [comment] 2018-07-20 07:03
yeah I updated twisted to 18.7 and it worked.

**Comment by andrewgodwin** [comment] 2018-07-22 16:53
Daphne `2.2.1` is now released with a Twisted 18.7 dependency to fix this.

**Closed by andrewgodwin** 2018-07-22 16:53 UTC
Labels: bug, exp/intermediate

**Comment by eamigo86** [comment] 2019-08-26 21:34
Hi @andrewgodwin, sorry for comment in this close issue but I am experiencing this same behavior with a new project that I am doing to learn Channels. 

<b>Description:</b> 
When I try to log in to the admin, it does not throw any error but it keeps "loading" the window. This behavior only happens in Chrome (76.0.3809.132), I have checked in Safari and it works perfectly.

Python 3.7.4, django-2.2.4, channels-2.2.0, daphne-2.3.0, asgiref-3.2.1, twisted-19.7.0

**Comment by carltongibson** [comment] 2019-08-27 13:26
Hi @eamigo86. Can you open a fresh issue? Perhaps create a minimal project with steps to reproduce. Happy to have a look.
