### ISSUE TITLE
Not able to see traceback exceptions on console with channels running 

### ISSUE THREAD

**Issue by tinson28** [django/channels#1381] opened 2019-11-12 02:55 UTC
I can't see any traceback exceptions on console when I enable channels in settings.py,if I remove it ,I can see the following traceback log :
Internal Server Error: /debug1/
Traceback (most recent call last):
..........
  File "/Users/tinson.liu/project/devops-admin/devops_admin/urls.py", line 8, in trigger_error1
    division_by_zero = 1 / 0
ZeroDivisionError: division by zero
 
I use the version of  python module with daphne==2.2.5,Django==2.1.7,channels 2.1.7.

**Comment by carltongibson** [comment] 2019-12-02 19:14
Duplicate of #1340, I think.

**Closed by carltongibson** 2019-12-02 19:14 UTC
