### ISSUE TITLE
Problem with binding save method to channels in model association scenario.   

### ISSUE THREAD

**Issue by naveen-varshney** [django/channels#702] opened 2017-07-14 05:28 UTC
Hey,
I am using Ubuntu 16.10 and Django 1.11.x and channels 1.3. 
The problem is when I tie send notification by overriding save method of a model and i want only to send notification when blog post(in my case) is created but if I make another channel for User Comment then save method of blog post again called due to association I guess.The point is if any changes take place related to Blog Post model duplication of notification occurs .

**Comment by naveen-varshney** [comment] 2017-07-14 05:31
I think problem can be solved by using signals..

**Comment by proofit404** [comment] 2017-07-14 05:33
Hi,

Instead of overriding `save` method move channels related logic into post save signal receiver. Created flag is available, so you can check it and send notification once.

Closing as this is not a bug in the Channels project.

**Closed by proofit404** 2017-07-14 05:33 UTC

**Comment by naveen-varshney** [comment] 2017-07-14 05:47
ok thanks ...I just followed one of the @andrewgodwin example "liveblog"  he used the same approach now i got it ...thanks sir and sorry for inconvenience.
