### ISSUE TITLE
ChannelLiveServerTestCase closes DB connection prematurely

### ISSUE THREAD

**Issue by jricardo27** [django/channels#614] opened 2017-04-18 01:01 UTC
Python:     3.5
Django:     1.11.0
Channels:   commit 5445d31
Daphne:     commit bd03fab
asgi_redis: 1.3.0
psycopg2: 2.7.1

Database:   Postgres
\-----------------------------

I'm using the new `ChannelLiveServerTestCase` in conjunction with `Aloe` (former `Lettuce`) for BDD testing.

The test:
- Opens the browser.
- Checks that "Hello World" is visible.
- It doesn't open a websocket.

It works when using `django.contrib.staticfiles.testing.StaticLiveServerTestCase` but not when using `ChannelLiveServerTestCase`.

It fails after finishing the test:
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/backends/utils.py", line 63, in execute
    return self.cursor.execute(sql)
psycopg2.DatabaseError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

The whole output can be seem at https://travis-ci.org/jricardo27/channels_example/builds/222972480

I set up a dummy project to reproduce this error, you can access the pull request at:
https://github.com/jricardo27/channels_example/pull/6

As I mentioned, running it with `StaticLiveServerTestCase` works:
https://github.com/jricardo27/channels_example/pull/7
Travis output for the successful test.
https://travis-ci.org/jricardo27/channels_example/builds/222975961

Full Traceback:
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/backends/utils.py", line 63, in execute
    return self.cursor.execute(sql)
psycopg2.DatabaseError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/test/testcases.py", line 216, in __call__
    self._post_teardown()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/channels/test/liveserver.py", line 224, in _post_teardown
    super(ChannelLiveServerTestCase, self)._post_teardown()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/test/testcases.py", line 925, in _post_teardown
    self._fixture_teardown()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/test/testcases.py", line 960, in _fixture_teardown
    inhibit_post_migrate=inhibit_post_migrate)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/commands/flush.py", line 54, in handle
    allow_cascade=allow_cascade)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/sql.py", line 15, in sql_flush
    tables = connection.introspection.django_table_names(only_existing=True, include_views=False)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/backends/base/introspection.py", line 86, in django_table_names
    existing_tables = self.table_names(include_views=include_views)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/backends/base/introspection.py", line 54, in table_names
    return get_names(cursor)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/backends/base/introspection.py", line 50, in get_names
    return sorted(ti.name for ti in self.get_table_list(cursor)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/backends/postgresql/introspection.py", line 67, in get_table_list
    AND pg_catalog.pg_table_is_visible(c.oid)""")
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/backends/utils.py", line 63, in execute
    return self.cursor.execute(sql)
django.db.utils.DatabaseError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

**Comment by proofit404** [comment] 2017-04-18 01:55
Thanks for such verbose example. I'll try to reproduce it.

**Comment by proofit404** [comment] 2017-04-19 20:25
I was able to reproduce mentioned behavior.

The problem lays somewhere in the multiprocessing access to the database. I've tried to change live server process bootstrap and teardown in every possible way I can imagine. No success.

Other things we can try:
* Maybe guys from aloe project can help
* Try to run your tests outside of nose.

**Comment by jricardo27** [comment] 2017-04-19 22:34
Thanks Artem, I will give it a try to both your suggestions.

**Comment by jricardo27** [comment] 2017-04-24 07:09
Hi @proofit404 I found that closing all DB connections before starting up the Worker and Daphne solves the problem.

Can you confirm if it is a proper solution, I'm at a lost when it comes to multiprocessing and how the whole test framework works.

You can check how tests pass after that change https://github.com/jricardo27/channels_example/pull/6

This is basically what I do.
```
class TestCase(ChannelLiveServerTestCase):
    def _pre_setup(self):
        connections.close_all()

        super()._pre_setup()
```

**Comment by proofit404** [comment] 2017-04-26 12:53
I can confirm that closing all connection make tests pass. Current behavior we have now:
- something closing underling pg connection without updating DatabaseWrapper attributes
- post tear down hook tries to flush database to remove fixtures
- this command failed because of already closed connection

I can't find what is the source of connection problem. Also I don't think we should blindly close connections without understanding of the actual problem.

**Comment by proofit404** [comment] 2017-05-23 16:12
Hopefully, I will be able to return to this issue at this weekend.

**Comment by proofit404** [comment] 2017-06-03 16:46
Working on this right now. Still, can't find the root of this problem.

**Closed** 2017-07-01 22:59 UTC
Labels: blocked/needs-investigation, bug, exp/advanced
