### ISSUE TITLE
took too long to shut down and was killed error

### ISSUE THREAD

**Issue by belongwqz** [django/channels#1685] opened 2021-04-22 08:18 UTC
OS: windowns7
django:3.1.8
channels:2.4.0
daphne:2.5.0
asgiref:3.2.10
channels_redis:3.1.0

I flow the channels doc from https://channels.readthedocs.io/ to create a django project with channels.
The I run `python manage.py runserver`, and I visit `http://localhost:8000` use chrome 90.
The console print some error like:
`Application instance <Task pending name='Task-8' coro=<AsgiHandler.__call__() running at D:\Python38\lib\site-packages\channels\http.py:192> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at D:\Python38\lib\asyncio\futures.py:360, <TaskWakeupMethWrapper object at 0x000000002B20F100>()]>> for connection <WebRequest at 0x2b4b2700 method=GET uri=/ clientproto=HTTP/1.1> took too long to shut down and was killed.`

And the chrome can not open the address `http://localhost:8000`, what I should do to find the hang reason?

**Comment by youssef-elmasry-lenme** [comment] 2021-06-27 12:44
I've similar issue, did you get a solution for this ? @belongwqz

**Comment by belongwqz** [comment] 2021-06-28 01:21
> I've similar issue, did you get a solution for this ? @belongwqz

Not yet, I just rollback to the old version.

**Comment by carltongibson** [comment] 2021-07-01 17:09
Duplicate of #1119

**Closed by carltongibson** 2021-07-01 17:09 UTC

**Comment by destelio** [comment] 2022-02-22 14:01
have you tried used the WebSocket reconnect library?

sources:
[https://github.com/joewalnes/reconnecting-websocket](url)
[https://www.npmjs.com/package/reconnecting-websocket](url)

you need to add this to your html:
```
<script src='https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.js'
></script>

```
and where you call WebSocket in JavaScript switch from **WebSocket** to  **ReconnectingWebSocket** 
`var socket = new ReconnectingWebSocket(endpoint) `

refresh you the browsers where you monitor messages (and incognito)

and it should work, i faced a similar issue... and this solution works for me.

kudos to justin mitchel, @https://github.com/codingforentrepreneurs   for this solution.

**Comment by carltongibson** [comment] 2022-02-22 14:33
Hey @destelio — thanks for mentioning that library. It may well be a handy resource to point to...
