### ISSUE TITLE
channels/docs/releases/4.0.0.rst install fix 15 line

### ISSUE THREAD

**Issue by guobiao-cn** [django/channels#1988] opened 2023-03-14 10:12 UTC
https://github.com/django/channels/blame/42760f9be5f66fd2dbf9b2e77fc84800a481b905/docs/releases/4.0.0.rst

old:pip install -U 'channels[dapne]' channels-redis

new:pip install -U 'channels[daphne]' channels-redis

**Comment by carltongibson** [comment] 2023-03-14 10:24
https://github.com/django/channels/commit/30ba81f22313baf3afde7f1a98c84109b21dfb93

Duplicate of #1935

**Closed by carltongibson** 2023-03-14 10:24 UTC
