### ISSUE TITLE
RuntimeError: Event loop is closed triggered randomly while trying to run tests form the original repo

### ISSUE THREAD

**Issue by sfehlandt** [django/channels#889] opened 2018-02-08 17:57 UTC
Hi, while trying to upgrade my project from Channels 1.x to Channels 2.x using pytest to test my consumers I found the following error after the tests pass:

`
======================================= 1 passed in 0.03 seconds =======================================
exception calling callback for <Future at 0x7f38bd050be0 state=finished returned list>
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.6/asyncio/futures.py", line 419, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 620, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
`

While trying to find the cause of this error, I copied and pasted in my project the test_generic.websockets.py file form this repo. Then I only executed those tests: `pytest myproject/test_generic_websocket.py`

As expected, the tests pass and I do not see the errors. 
However, If I delete (or comment) the tests and only run the test for the AsyncWebsocketConsumer I see the errors again.

In order to isolate possible causes I created a clean minimal working example: https://github.com/sfehlandt/channels2_example
This is just a Django Channels 2 project with 1 app and I copied the entire test_generic.websockets.py file from the channels repo. I reproduced the configuration from the instructions on the documentation.

Again, If I run all the test I have no issues, but if I run 1 or both of the tests for the async consumers the error is still triggered. If I keep at least one of the sync test I have no errors, If I remove both of them I have the errors.

This does not happen always, it happens randomly but very frequently.
You can fork and clone my example and execute pytest in order to reproduce the errors.

- OS: Ubuntu 16.04.1 64 bits. Virtualenvironment with python 3.6.3
- Versions:
aioredis==1.0.0
asgiref==2.1.4
async-timeout==2.0.0
attrs==17.4.0
autobahn==17.10.1
Automat==0.6.0
channels==2.0.2
channels-redis==2.0.2
constantly==15.1.0
daphne==2.0.3
Django==2.0.2
hiredis==0.2.0
hyperlink==17.3.1
incremental==17.5.0
msgpack==0.5.4
pkg-resources==0.0.0
pluggy==0.6.0
py==1.5.2
pytest==3.4.0
pytest-asyncio==0.8.0
pytest-django==3.1.2
pytz==2017.3
six==1.11.0
Twisted==17.9.0
txaio==2.8.2
zope.interface==4.4.3

- What you expected to happen vs. what actually happened:
I expected no errors, but I have these errors randomly

- How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)
I am just testing for now, so: `pytest`

- Console logs and full tracebacks of any errors
======================================= 1 passed in 0.03 seconds =======================================
exception calling callback for <Future at 0x7f38bd050be0 state=finished returned list>
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.6/asyncio/futures.py", line 419, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 620, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
`

**Comment by andrewgodwin** [comment] 2018-02-08 18:10
Can you turn off the Redis channel layer? I believe the problem is in there, so it would be good to verify the test runs better without it.

**Comment by sfehlandt** [comment] 2018-02-08 18:27
Hi, thank you very much for your quick reply.

Yes, if I delete this from the settings file:
`
redis_host = os.environ.get('REDIS_HOST', 'localhost')
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(redis_host, 6379)],
        }
    },
}
`
I stop getting the errors.

Does this mean there is a problem in the channel-redis library?
Should we try to use another channel layer?
BTW, did you try this? do you get the error as well?

**Comment by andrewgodwin** [comment] 2018-02-08 18:41
Yes, then this is a duplicate of https://github.com/django/channels/issues/859, so closing this in favour of that.

I haven't tried it myself, as I don't have time to replicate yet, but the error you are getting is very similar to other people (see that other issue), and turning off channels_redis indicates it's a problem there. I even have a suspicion what the problem is, but I need to get time to sit down, replicate it, and fix it.

**Closed by andrewgodwin** 2018-02-08 18:41 UTC
Labels: bug, exp/intermediate
