### ISSUE TITLE
AsyncToSync(self.channel_layer.group_add) fails with There is no current event loop in thread

### ISSUE THREAD

**Issue by marakaci** [django/channels#877] opened 2018-02-07 12:26 UTC
I've been following the docs, so I try to add the current channel to the group.
from asgiref.sync import AsyncToSync
from channels.generic.websocket import JsonWebsocketConsumer
class PrivateChatConsumer(JsonWebsocketConsumer):
  def connect(self):
    self.accept()
    AsyncToSync(self.channel_layer.group_add)('chat', self.channel_name)
    ....
settings 
....
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],
        },
    },
}
ASGI_APPLICATION = "backend.routing.application"
...

Django==2.0.1
Twisted==17.9.0
channels==2.0.1
channels-redis==2.0.0
daphne==2.0.2
I run this under Docker (maybe this will be useful). I also have redis 2.10.6 installed. Everything works fine if I use AsyncJsonWebsocketConsumer,
This leads to the following error:
2018-02-07 12:18:15,858 - ERROR - server - Exception inside application: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.
  File "/usr/local/lib/python3.6/site-packages/channels/consumer.py", line 53, in __call__
    await await_many_dispatch([receive, self.channel_receive], self.dispatch)
  File "/usr/local/lib/python3.6/site-packages/channels/utils.py", line 48, in await_many_dispatch
    await dispatch(result)
  File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 81, in inner
    return await async_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 65, in __call__
    return await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 74, in thread_handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 72, in thread_handler
    self.func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/channels/consumer.py", line 98, in dispatch
    handler(message)
  File "/usr/local/lib/python3.6/site-packages/channels/generic/websocket.py", line 19, in websocket_connect
    self.connect()
  File "/opt/project/backend/chat/consumers.py", line 41, in connect
    raise e
  File "/opt/project/backend/chat/consumers.py", line 37, in connect
    AsyncToSync(self.channel_layer.group_add)('chat', self.channel_name)
  File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 17, in __init__
    self.main_event_loop = asyncio.get_event_loop()
  File "/usr/local/lib/python3.6/asyncio/events.py", line 694, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/usr/local/lib/python3.6/asyncio/events.py", line 602, in get_event_loop
    % threading.current_thread().name)
  There is no current event loop in thread 'ThreadPoolExecutor-0_0'.

**Comment by marakaci** [comment] 2018-02-07 12:47
Solution from https://github.com/django/channels/issues/859
 ...
    async def async_group_add(self, *args, **kwargs):
        self.channel_layer.group_add(*args, **kwargs)
    group_add = AsyncToSync(async_group_add)

    def connect(self):
        self.group_add(...)
worked

**Comment by andrewgodwin** [comment] 2018-02-07 18:13
Duplicate of https://github.com/django/channels/issues/859 (that workaround didn't work there either). Working on that today.

**Closed by andrewgodwin** 2018-02-07 18:13 UTC
