### ISSUE TITLE
[Failure instance: Traceback: <class 'ValueError'>: No route found for path 'socketcluster/'.

### ISSUE THREAD

**Issue by soleyj** [django/channels#1543] opened 2020-10-28 08:59 UTC
Hello I have used django + channels without any problem for a few month.

But recently I have found this issue:

`[Failure instance: Traceback: <class 'ValueError'>: No route found for path 'socketcluster/'.
/home/ssoleyj/Documents/GitHub/escapingio/env/lib/python3.6/site-packages/autobahn/websocket/protocol.py:2847:processHandshake
/home/ssoleyj/Documents/GitHub/escapingio/env/lib/python3.6/site-packages/txaio/tx.py:366:as_future
/home/ssoleyj/Documents/GitHub/escapingio/env/lib/python3.6/site-packages/twisted/internet/defer.py:151:maybeDeferred
/home/ssoleyj/Documents/GitHub/escapingio/env/lib/python3.6/site-packages/daphne/ws_protocol.py:83:onConnect
--- <exception caught here> ---
/home/ssoleyj/Documents/GitHub/escapingio/env/lib/python3.6/site-packages/twisted/internet/defer.py:151:maybeDeferred
/home/ssoleyj/Documents/GitHub/escapingio/env/lib/python3.6/site-packages/daphne/server.py:200:create_application
/home/ssoleyj/Documents/GitHub/escapingio/env/lib/python3.6/site-packages/channels/staticfiles.py:41:__call__
/home/ssoleyj/Documents/GitHub/escapingio/env/lib/python3.6/site-packages/channels/routing.py:54:__call__
/home/ssoleyj/Documents/GitHub/escapingio/env/lib/python3.6/site-packages/channels/sessions.py:47:__call__
/home/ssoleyj/Documents/GitHub/escapingio/env/lib/python3.6/site-packages/channels/sessions.py:145:__call__
/home/ssoleyj/Documents/GitHub/escapingio/env/lib/python3.6/site-packages/channels/sessions.py:169:__init__
/home/ssoleyj/Documents/GitHub/escapingio/env/lib/python3.6/site-packages/channels/middleware.py:31:__call__
/home/ssoleyj/Documents/GitHub/escapingio/env/lib/python3.6/site-packages/channels/routing.py:150:__call__
]
WebSocket DISCONNECT /socketcluster/ [127.0.0.1:54978]`

I can't realize this error come from, I don't have any /socketcluster route in my software.

Also, the error seams to be random.

I'm running the software on ubuntu 18.04, and I will attach the requirements file, but I didn't update it between the error appear.

`aioredis==1.3.1
APScheduler==3.6.3
asgi-redis==1.4.3
asgiref==3.2.10
astroid==2.3.3
async-timeout==3.0.1
attrs==19.3.0
autobahn==20.4.2
Automat==20.2.0
backcall==0.1.0
bleach==3.1.4
bootstrap4==0.1.0
certifi==2020.4.5.2
cffi==1.14.0
channels==2.4.0
channels-redis==2.4.2
chardet==3.0.4
constantly==15.1.0
cryptography==2.9
daphne==2.5.0
decorator==4.4.2
defusedxml==0.6.0
Django==3.1.1
django-crispy-forms==1.9.0
django-extensions==2.2.9
django-pandas==0.6.1
django-smtp-ssl==1.0
entrypoints==0.3
hiredis==1.0.1
hyperlink==19.0.0
idna==2.9
importlib-metadata==1.6.0
incremental==17.5.0
ipykernel==5.2.1
ipython==7.13.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
jedi==0.17.0
Jinja2==2.11.2
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.3
jupyter-console==6.1.0
jupyter-core==4.6.3
lazy-object-proxy==1.4.3
MarkupSafe==1.1.1
mccabe==0.6.1
mistune==0.8.4
msgpack==0.6.2
msgpack-python==0.5.6
nbconvert==5.6.1
nbformat==5.0.6
notebook==6.0.3
numpy==1.18.3
pandas==1.0.3
pandocfilters==1.4.2
parso==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.1.1
prometheus-client==0.7.1
prompt-toolkit==3.0.5
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
Pygments==2.6.1
PyHamcrest==2.0.2
pylint==2.4.4
pyOpenSSL==19.1.0
pyrsistent==0.16.0
python-dateutil==2.8.1
pytz==2019.3
pyzmq==19.0.0
qtconsole==4.7.3
QtPy==1.9.0
redis==2.10.6
requests==2.23.0
schedule==0.6.0
Send2Trash==1.5.0
service-identity==18.1.0
six==1.14.0
sqlparse==0.3.1
stripe==2.48.0
terminado==0.8.3
testpath==0.4.4
tornado==6.0.4
traitlets==4.3.3
Twisted==20.3.0
txaio==20.4.1
typed-ast==1.4.1
tzlocal==2.1
Unidecode==1.1.1
urllib3==1.25.9
wcwidth==0.1.9
webencodings==0.5.1
widgetsnbextension==3.5.1
wrapt==1.11.2
zipp==3.1.0
zope.interface==5.1.0
`

Thanks

**Comment by carltongibson** [comment] 2020-10-28 09:20
Duplicate of https://github.com/django/channels/discussions/1490

**Closed by carltongibson** 2020-10-28 09:20 UTC
