### ISSUE TITLE
django.core.exceptions.SynchronousOnlyOperation after upgrading django to 3.0

### ISSUE THREAD

**Issue by LukenAgile42** [django/channels#1464] opened 2020-07-10 07:11 UTC
I get 
`django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.`
after upgrading to django 3.0

The suggestion of using `sync_to_async` does not fix the issue. I was following the example in the [documentation](https://channels.readthedocs.io/en/latest/topics/testing.html#).

```
    @pytest.mark.django_db
    @pytest.mark.asyncio
    async def test_strategy_map_ws(self):
        MyModel.create(...)
        communicator = WebsocketCommunicator(...)
        connected, subprotocol = await communicator.connect()
```
Here, wrapping `communicator.connect` and `MyModel.objects.create` in `sync_to_async` or `database_sync_to_async` made no difference. I have tried to workaround a little by moving these things outside of the test, but this is a not a complete solution , , as this problem is occurring everywhere in my code where `sync_to_async` should have worked.

**Comment by carltongibson** [comment] 2020-07-10 07:33
Hi @LukenAgile42. 

So you certainly need to wrap `MyModel.create(...)` (assuming that's a ORM operation... — why not MyModel.objects.create(...)? — don't worry, let's not get sidetracked) in `sync_to_async` (or the database version). 

Could you post the whole traceback? Impossible to see fully from what you've pasted.

**Comment by LukenAgile42** [comment] 2020-07-10 08:53
This was working before the upgrade though, even without wrapping sync functions (I thought pytest-async took care of this?).

```
Traceback (most recent call last):
  File "...lib/python3.6/site-packages/asgiref/testing.py", line 74, in receive_output
    return await self.output_queue.get()
  File ".../lib/python3.6/asyncio/queues.py", line 167, in get
    yield from getter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...lib/python3.6/site-packages/asgiref/testing.py", line 74, in receive_output
    return await self.output_queue.get()
  File ".../lib/python3.6/site-packages/asgiref/timeout.py", line 68, in __aexit__
    self._do_exit(exc_type)
  File ".../lib/python3.6/site-packages/asgiref/timeout.py", line 105, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../lib/python3.6/site-packages/asynctest/case.py", line 297, in run
    self._run_test_method(testMethod)
  File "/.../lib/python3.6/site-packages/asynctest/case.py", line 354, in _run_test_method
    self.loop.run_until_complete(result)
  File "...lib/python3.6/site-packages/asynctest/case.py", line 224, in wrapper
    return method(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "...", line 98, in tes_ws
    connected, subprotocol = await communicator.connect()
  File ".../lib/python3.6/site-packages/channels/testing/websocket.py", line 36, in connect
    response = await self.receive_output(timeout)
  File ".../lib/python3.6/site-packages/asgiref/testing.py", line 78, in receive_output
    self.future.result()
  File ".../lib/python3.6/site-packages/asgiref/compatibility.py", line 33, in new_application
    instance = application(scope)
  File ".../lib/python3.6/site-packages/channels/routing.py", line 54, in __call__
    return self.application_mapping[scope["type"]](scope)
  File ".../lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
    return self.inner(dict(scope, cookies=cookies))
  File ".../lib/python3.6/site-packages/channels/sessions.py", line 145, in __call__
    return SessionMiddlewareInstance(scope, self)
  File ".../lib/python3.6/site-packages/channels/sessions.py", line 169, in __init__
    self.inner = self.middleware.inner(self.scope)
  File "...", line 32, in __call__
    tenant = Client.objects.get(domain_url=hostname)
  File ".../lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/...lib/python3.6/site-packages/django/db/models/query.py", line 411, in get
    num = len(clone)
  File "...lib/python3.6/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "...lib/python3.6/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File ".../lib/python3.6/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File ".../lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1135, in execute_sql
    cursor = self.connection.cursor()
  File ".../lib/python3.6/site-packages/django/utils/asyncio.py", line 22, in inner
    raise SynchronousOnlyOperation(message)
django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.


```

**Comment by carltongibson** [comment] 2020-07-10 09:14
Yes, Django 3.0 introduced `SynchronousOnlyOperation`. ([See the release notes](https://docs.djangoproject.com/en/3.0/releases/3.0/#asgi-support).) This kind of thing wasn't safe before, but now we enforce that you can't do it. 

 Looks like you're on an old version of Channels: 

```
  File ".../lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
    return self.inner(dict(scope, cookies=cookies))
  File ".../lib/python3.6/site-packages/channels/sessions.py", line 145, in __call__
    return SessionMiddlewareInstance(scope, self)
  File ".../lib/python3.6/site-packages/channels/sessions.py", line 169, in __init__
    self.inner = self.middleware.inner(self.scope)
  File "...", line 32, in __call__
    tenant = Client.objects.get(domain_url=hostname)
  File ".../lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
```

This should be resolved by 277f6957020479f54fed198063d1945b7787437a which was in 2.4.0. 

Please let me know if that's not the case.

**Closed by carltongibson** 2020-07-10 09:14 UTC

**Comment by LukenAgile42** [comment] 2020-07-10 10:25
> This kind of thing wasn't safe before, but now we enforce that you can't do it.

Then it seems the docs are not updated to using Django 3.0.

I'm had been upgraded to channels 2.4.0 during debugging, but it seems I have a different error for this.

```
@pytest.mark.django_db
    @pytest.mark.asyncio
    async def test_strategy_map_ws(self):
        myModel = database_sync_to_async(MyModel.objects.create)(...)
        myModel.myField()
```
gives

```
Error
Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/asynctest/case.py", line 297, in run
    self._run_test_method(testMethod)
  File ".../lib/python3.6/site-packages/asynctest/case.py", line 354, in _run_test_method
    self.loop.run_until_complete(result)
  File ".../lib/python3.6/site-packages/asynctest/case.py", line 224, in wrapper
    return method(*args, **kwargs)
  File ".../lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "...", line 96, in test_ws
AttributeError: 'coroutine' object has no attribute 'myField'
```

**Comment by carltongibson** [comment] 2020-07-10 10:31
> Then it seems the docs are not updated to using Django 3.0.

Yes, good catch! If you make a PR whilst you're here then that would be awesome! Thanks! 🥇 

> AttributeError: 'coroutine' object has no attribute 'myField'

You have to await the coroutine.

**Comment by LukenAgile42** [comment] 2020-07-10 10:47
I can do that if I actually get the channels stuff working again.

Adding back in
`myModel = await database_sync_to_async(MyModel.objects.create)(...)`
gives back the original error.

**Comment by carltongibson** [comment] 2020-07-10 10:56
Still gonna need the traceback... 🙂

Can you upload a minimal reproduce? There's very little that's possible in this piece-meal report kind of way...

**Comment by LukenAgile42** [comment] 2020-07-10 11:14
Fair enough, but its basically the same.

```
Error
Traceback (most recent call last):
  File "lib/python3.6/site-packages/asynctest/case.py", line 297, in run
    self._run_test_method(testMethod)
  File "lib/python3.6/site-packages/asynctest/case.py", line 354, in _run_test_method
    self.loop.run_until_complete(result)
  File "lib/python3.6/site-packages/asynctest/case.py", line 224, in wrapper
    return method(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "", line 86, in test_strategy_map_ws
    await database_sync_to_async(MyModel.objects.create)()
  File "lib/python3.6/site-packages/asgiref/sync.py", line 296, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "lib/python3.6/site-packages/channels/db.py", line 14, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "lib/python3.6/site-packages/asgiref/sync.py", line 334, in thread_handler
    return func(*args, **kwargs)
  File "lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "lib/python3.6/site-packages/django/db/models/query.py", line 433, in create
    obj.save(force_insert=True, using=self.db)
  File "lib/python3.6/site-packages/polymorphic/models.py", line 92, in save
    self.pre_save_polymorphic(using=using)
  File "lib/python3.6/site-packages/polymorphic/models.py", line 85, in pre_save_polymorphic
    ).get_for_model(self, for_concrete_model=False)
  File "lib/python3.6/site-packages/django/contrib/contenttypes/models.py", line 51, in get_for_model
    ct = self.get(app_label=opts.app_label, model=opts.model_name)
  File "lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "lib/python3.6/site-packages/django/db/models/query.py", line 411, in get
    num = len(clone)
  File "lib/python3.6/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "lib/python3.6/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "lib/python3.6/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1135, in execute_sql
    cursor = self.connection.cursor()
  File "lib/python3.6/site-packages/django/utils/asyncio.py", line 22, in inner
    raise SynchronousOnlyOperation(message)
django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.

```

**Comment by LukenAgile42** [comment] 2020-07-10 11:18
As far as minimal reproduction, theres not really anything else happening...I have a test, I'm trying to do ORM stuff and `sync_to_async` isnt working. Thats it.

**Comment by carltongibson** [comment] 2020-07-10 11:23
I think you need to look at `pre_save_polymorphic`.

**Comment by carltongibson** [comment] 2020-07-10 12:00
I suspect if you try to create a clean slate project just using asgiref and a simple model, that this won’t happen, or you’ll find you issue. 

If not though we’d have a reproduce. 

I hope that makes sense.

**Comment by LukenAgile42** [comment] 2020-07-10 12:41
`I think you need to look at pre_save_polymorphic.`

That doesnt seem to be it. When I use regular non polymorphic model (or `WebsocketCommunicator().connect`) I still get this error.

```       
  File "lib/python3.6/site-packages/asynctest/case.py", line 297, in run
    self._run_test_method(testMethod)
  File "lib/python3.6/site-packages/asynctest/case.py", line 354, in _run_test_method
    self.loop.run_until_complete(result)
  File "lib/python3.6/site-packages/asynctest/case.py", line 224, in wrapper
    return method(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "...", line 88, in test_ws
    is_available=True,
  File "lib/python3.6/site-packages/asgiref/sync.py", line 296, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "lib/python3.6/site-packages/channels/db.py", line 14, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "lib/python3.6/site-packages/asgiref/sync.py", line 334, in thread_handler
    return func(*args, **kwargs)
  File "lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "lib/python3.6/site-packages/django/db/models/query.py", line 433, in create
    obj.save(force_insert=True, using=self.db)
  File "lib/python3.6/site-packages/django/db/models/base.py", line 746, in save
    force_update=force_update, update_fields=update_fields)
  File "lib/python3.6/site-packages/django/db/models/base.py", line 784, in save_base
    force_update, using, update_fields,
  File "lib/python3.6/site-packages/django/db/models/base.py", line 886, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "lib/python3.6/site-packages/django/db/models/base.py", line 925, in _do_insert
    using=using, raw=raw,
  File "lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "lib/python3.6/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1375, in execute_sql
    with self.connection.cursor() as cursor:
  File "lib/python3.6/site-packages/django/utils/asyncio.py", line 22, in inner
    raise SynchronousOnlyOperation(message)
django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.
```

**Comment by LukenAgile42** [comment] 2020-07-10 12:53
Specifically I also get this error for `WebsocketCommunicator`. Even though I use `await`.

```

/.../lib/python3.6/asyncio/base_events.py:1452: RuntimeWarning: coroutine 'WebsocketCommunicator.connect' was never awaited
  handle = None  # Needed to break cycles when an exception occurs.

Error
Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/asynctest/case.py", line 297, in run
    self._run_test_method(testMethod)
  File ".../lib/python3.6/site-packages/asynctest/case.py", line 354, in _run_test_method
    self.loop.run_until_complete(result)
  File ".../lib/python3.6/site-packages/asynctest/case.py", line 224, in wrapper
    return method(*args, **kwargs)
  File ".../lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/.../tests/tests.py", line 103, in test_ws
    connected, subprotocol = await database_sync_to_async(communicator.connect)()
TypeError: 'coroutine' object is not iterable
```
